apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
  labels:
    name: volume-1
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/docker/volumes/volume1
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example-2
  labels:
    name: volume-2
    type: local-2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/docker/volumes/volume2
