apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: development
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: development
data:
  MYSQL_DATABASE: exdb
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    db: mysql-db
  namespace: development
spec:
  containers:
    - name: mysql-db
      image: mysql:latest
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-configmap
      ports:
        - containerPort: 3306
